[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask-cors>=6.0.0",
    "flask[async]>=3.1.1",
    "openai-agents>=0.0.17",
]
